apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-golang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-golang
  template:
    metadata:
      labels:
        app: rest-golang
    spec:
      containers:
        - name: rest-golang
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 75m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 100Mi
      restartPolicy: Always
